sudo: false

language: php

php:
  - hhvm
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
